title: <p align="center"> Bethan Cordone </p> # your name (or website title) here

logo: "/images/logo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bethan-cordone/">LinkedIn</a>
  </p>
  
  <p align="justify">
  I am a recent graduate from Columbia Engineering with experience in Applied Physics and Applied Statistics. 
  I have channeled my innate passion for problem solving into honing the skills required to extract value from data 
  and have developed a particular interest in the application of data analytics tools in energy solutions.  
  I am currently working on additional data analytics projects and looking for further opportunities to develop my skills.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
